[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/golang/mock"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.9.1"

[[override]]
  name = "k8s.io/kubernetes"
  branch = "release-1.9"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[override]]
  name = "google.golang.org/grpc"
  revision = "5ffe3083946d5603a0578721101dc8165b1d5b5f"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"
